import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { execSync } from "node:child_process";
import { readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const prod = process.argv[2] === "production";

/** Every `.md` under a directory — the Help content the module graph never
 * imports directly, so esbuild's watcher has to be told about it by hand. */
function markdownFiles(dir, out = []) {
	for (const name of readdirSync(dir)) {
		const full = join(dir, name);
		if (statSync(full).isDirectory()) markdownFiles(full, out);
		else if (name.endsWith(".md")) out.push(full);
	}
	return out;
}

const helpContentPlugin = {
	name: "help-content",
	setup(build) {
		// Regenerate before every build, including the first one in watch mode.
		build.onStart(() => {
			execSync("node scripts/build-help.mjs", { stdio: "inherit" });
			execSync("node scripts/build-templates.mjs", { stdio: "inherit" });
		});
		// Nothing in the graph imports the `.md` files, so register them as
		// watch inputs against the generated module that stands in for them.
		build.onLoad({ filter: /help-generated\.ts$/ }, () => ({
			watchFiles: markdownFiles("src/help-content"),
		}));
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [helpContentPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	jsx: "automatic",
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
