/**
 * The icon set for Workspaces, Views, and Projects.
 *
 * A stored icon is one of these string ids (persisted in `_views.md`, a project
 * note's frontmatter, or `_workspace.md`). `<Icon>` renders one by id;
 * `<IconField>` is the trigger-plus-searchable-grid used in the create/edit
 * dialogs. The ids are the kebab-case Lucide names, so they read sensibly in
 * frontmatter and stay stable if the set grows.
 */

import { useEffect, useMemo, useState, type ComponentType } from "react";
import {
	List,
	ListChecks,
	ListTodo,
	ListTree,
	ListOrdered,
	AlignLeft,
	Rows3,
	Columns3,
	Columns4,
	LayoutGrid,
	LayoutList,
	LayoutDashboard,
	LayoutPanelLeft,
	Kanban,
	Table,
	Table2,
	Grid3x3,
	SquareStack,
	Layers,
	Layers2,
	Boxes,
	Box,
	Package,
	PackageOpen,
	Archive,
	ArchiveRestore,
	Inbox,
	Mail,
	MailOpen,
	Send,
	Bell,
	BellRing,
	CircleDot,
	Circle,
	CircleCheck,
	CircleCheckBig,
	CircleAlert,
	CircleHelp,
	CircleSlash,
	Target,
	Crosshair,
	Goal,
	Flag,
	FlagTriangleRight,
	Milestone,
	Trophy,
	Medal,
	Award,
	Crown,
	Gem,
	Diamond,
	Folder,
	FolderOpen,
	FolderKanban,
	FolderGit2,
	FolderTree,
	FolderClock,
	FolderCheck,
	File as FileIcon,
	FileText,
	Files,
	FileCode,
	FileStack,
	Notebook,
	NotebookPen,
	BookOpen,
	Book,
	BookMarked,
	Library,
	Clipboard,
	ClipboardList,
	ClipboardCheck,
	Rocket,
	Zap,
	Flame,
	Sparkle,
	Sparkles,
	Star,
	Heart,
	Bookmark,
	BookmarkCheck,
	Pin,
	PinOff,
	Tag,
	Tags,
	Hash,
	AtSign,
	Percent,
	Bug,
	BugPlay,
	Wrench,
	Hammer,
	Cog,
	Settings,
	Settings2,
	SlidersHorizontal,
	Sliders,
	Terminal,
	Code,
	Code2,
	GitBranch,
	GitCommitHorizontal,
	GitPullRequest,
	GitMerge,
	Braces,
	Binary,
	Database,
	Server,
	Cpu,
	HardDrive,
	Cloud,
	CloudUpload,
	Users,
	User,
	UserPlus,
	UserCheck,
	UsersRound,
	Contact,
	Handshake,
	MessageSquare,
	MessageCircle,
	MessagesSquare,
	Speech,
	Megaphone,
	Phone,
	Video,
	Calendar,
	CalendarDays,
	CalendarCheck,
	CalendarClock,
	CalendarRange,
	Clock,
	Clock3,
	Timer,
	Hourglass,
	History as HistoryIcon,
	AlarmClock,
	ChartBar,
	BarChart3,
	ChartLine,
	LineChart,
	ChartPie,
	PieChart,
	TrendingUp,
	TrendingDown,
	Activity,
	Gauge,
	Signal,
	Radar,
	Search,
	Filter,
	Funnel,
	Eye,
	EyeOff,
	Bolt,
	Lightbulb,
	Brain,
	Compass,
	Map as MapIcon,
	MapPin,
	Navigation as NavigationIcon,
	Route,
	Waypoints,
	Workflow,
	Network,
	Share2,
	Link,
	Link2,
	Paperclip,
	Palette,
	Brush,
	Paintbrush,
	PenTool,
	Pencil,
	Edit3,
	Type,
	Image as ImageIcon,
	Camera,
	Film,
	Music,
	Headphones,
	Mic,
	ShoppingCart,
	ShoppingBag,
	CreditCard,
	DollarSign,
	Wallet,
	Receipt,
	Banknote,
	Coins,
	Briefcase,
	Building,
	Building2,
	Home,
	House,
	Store,
	Factory,
	Warehouse,
	Shield,
	ShieldCheck,
	Lock,
	Unlock,
	Key,
	KeyRound,
	Fingerprint,
	ScanFace,
	Truck,
	Plane,
	Car,
	Bike,
	Ship,
	Globe,
	Globe2,
	Languages,
	Plug,
	Power,
	Battery,
	Wifi,
	Rss,
	Leaf,
	TreePine,
	Flower2,
	Sun,
	Moon,
	CloudRain,
	Snowflake,
	Droplet,
	Wind,
	Mountain,
	Waves,
	Anchor,
	Coffee,
	Pizza,
	Apple,
	Utensils,
	Cake,
	Beer,
	Dumbbell,
	Footprints,
	Puzzle,
	Gamepad2,
	Dice5,
	Swords,
	Wand2,
	Ghost,
	Bot,
	Atom,
	FlaskConical,
	Microscope,
	Telescope,
	Beaker,
	Stethoscope,
	Pill,
	HeartPulse,
	ThumbsUp,
	Smile,
	Laugh,
	PartyPopper,
	Gift,
	Volume2,
	Play,
	Pause,
	SkipForward,
	Repeat,
	Shuffle,
	ArrowRight,
	ArrowUpRight,
	CornerDownRight,
	Move,
	Maximize2,
	Minimize2,
	Expand,
	Shrink,
	RefreshCw,
	RotateCw,
	Undo2,
	Redo2,
	Download,
	Upload,
	Save,
	Trash2,
	Copy,
	Scissors,
	CheckCheck,
	Check,
	X,
	Plus,
	Minus,
} from "lucide-react";

type IconComponent = ComponentType<{ size?: number | string; className?: string }>;

export interface IconEntry {
	id: string;
	label: string;
	Icon: IconComponent;
}

export const ICONS: IconEntry[] = [
	{ id: "list", label: "List", Icon: List },
	{ id: "list-checks", label: "List Checks", Icon: ListChecks },
	{ id: "list-todo", label: "List Todo", Icon: ListTodo },
	{ id: "list-tree", label: "List Tree", Icon: ListTree },
	{ id: "list-ordered", label: "List Ordered", Icon: ListOrdered },
	{ id: "align-left", label: "Align Left", Icon: AlignLeft },
	{ id: "rows-3", label: "Rows 3", Icon: Rows3 },
	{ id: "columns-3", label: "Columns 3", Icon: Columns3 },
	{ id: "columns-4", label: "Columns 4", Icon: Columns4 },
	{ id: "layout-grid", label: "Layout Grid", Icon: LayoutGrid },
	{ id: "layout-list", label: "Layout List", Icon: LayoutList },
	{ id: "layout-dashboard", label: "Layout Dashboard", Icon: LayoutDashboard },
	{ id: "layout-panel-left", label: "Layout Panel Left", Icon: LayoutPanelLeft },
	{ id: "kanban", label: "Kanban", Icon: Kanban },
	{ id: "table", label: "Table", Icon: Table },
	{ id: "table-2", label: "Table 2", Icon: Table2 },
	{ id: "grid-3x3", label: "Grid", Icon: Grid3x3 },
	{ id: "square-stack", label: "Square Stack", Icon: SquareStack },
	{ id: "layers", label: "Layers", Icon: Layers },
	{ id: "layers-2", label: "Layers 2", Icon: Layers2 },
	{ id: "boxes", label: "Boxes", Icon: Boxes },
	{ id: "box", label: "Box", Icon: Box },
	{ id: "package", label: "Package", Icon: Package },
	{ id: "package-open", label: "Package Open", Icon: PackageOpen },
	{ id: "archive", label: "Archive", Icon: Archive },
	{ id: "archive-restore", label: "Archive Restore", Icon: ArchiveRestore },
	{ id: "inbox", label: "Inbox", Icon: Inbox },
	{ id: "mail", label: "Mail", Icon: Mail },
	{ id: "mail-open", label: "Mail Open", Icon: MailOpen },
	{ id: "send", label: "Send", Icon: Send },
	{ id: "bell", label: "Bell", Icon: Bell },
	{ id: "bell-ring", label: "Bell Ring", Icon: BellRing },
	{ id: "circle-dot", label: "Circle Dot", Icon: CircleDot },
	{ id: "circle", label: "Circle", Icon: Circle },
	{ id: "circle-check", label: "Circle Check", Icon: CircleCheck },
	{ id: "circle-check-big", label: "Circle Check Big", Icon: CircleCheckBig },
	{ id: "circle-alert", label: "Circle Alert", Icon: CircleAlert },
	{ id: "circle-help", label: "Circle Help", Icon: CircleHelp },
	{ id: "circle-slash", label: "Circle Slash", Icon: CircleSlash },
	{ id: "target", label: "Target", Icon: Target },
	{ id: "crosshair", label: "Crosshair", Icon: Crosshair },
	{ id: "goal", label: "Goal", Icon: Goal },
	{ id: "flag", label: "Flag", Icon: Flag },
	{ id: "flag-triangle-right", label: "Flag Triangle Right", Icon: FlagTriangleRight },
	{ id: "milestone", label: "Milestone", Icon: Milestone },
	{ id: "trophy", label: "Trophy", Icon: Trophy },
	{ id: "medal", label: "Medal", Icon: Medal },
	{ id: "award", label: "Award", Icon: Award },
	{ id: "crown", label: "Crown", Icon: Crown },
	{ id: "gem", label: "Gem", Icon: Gem },
	{ id: "diamond", label: "Diamond", Icon: Diamond },
	{ id: "folder", label: "Folder", Icon: Folder },
	{ id: "folder-open", label: "Folder Open", Icon: FolderOpen },
	{ id: "folder-kanban", label: "Folder Kanban", Icon: FolderKanban },
	{ id: "folder-git-2", label: "Folder Git 2", Icon: FolderGit2 },
	{ id: "folder-tree", label: "Folder Tree", Icon: FolderTree },
	{ id: "folder-clock", label: "Folder Clock", Icon: FolderClock },
	{ id: "folder-check", label: "Folder Check", Icon: FolderCheck },
	{ id: "file", label: "File", Icon: FileIcon },
	{ id: "file-text", label: "File Text", Icon: FileText },
	{ id: "files", label: "Files", Icon: Files },
	{ id: "file-code", label: "File Code", Icon: FileCode },
	{ id: "file-stack", label: "File Stack", Icon: FileStack },
	{ id: "notebook", label: "Notebook", Icon: Notebook },
	{ id: "notebook-pen", label: "Notebook Pen", Icon: NotebookPen },
	{ id: "book-open", label: "Book Open", Icon: BookOpen },
	{ id: "book", label: "Book", Icon: Book },
	{ id: "book-marked", label: "Book Marked", Icon: BookMarked },
	{ id: "library", label: "Library", Icon: Library },
	{ id: "clipboard", label: "Clipboard", Icon: Clipboard },
	{ id: "clipboard-list", label: "Clipboard List", Icon: ClipboardList },
	{ id: "clipboard-check", label: "Clipboard Check", Icon: ClipboardCheck },
	{ id: "rocket", label: "Rocket", Icon: Rocket },
	{ id: "zap", label: "Zap", Icon: Zap },
	{ id: "flame", label: "Flame", Icon: Flame },
	{ id: "sparkle", label: "Sparkle", Icon: Sparkle },
	{ id: "sparkles", label: "Sparkles", Icon: Sparkles },
	{ id: "star", label: "Star", Icon: Star },
	{ id: "heart", label: "Heart", Icon: Heart },
	{ id: "bookmark", label: "Bookmark", Icon: Bookmark },
	{ id: "bookmark-check", label: "Bookmark Check", Icon: BookmarkCheck },
	{ id: "pin", label: "Pin", Icon: Pin },
	{ id: "pin-off", label: "Pin Off", Icon: PinOff },
	{ id: "tag", label: "Tag", Icon: Tag },
	{ id: "tags", label: "Tags", Icon: Tags },
	{ id: "hash", label: "Hash", Icon: Hash },
	{ id: "at-sign", label: "At Sign", Icon: AtSign },
	{ id: "percent", label: "Percent", Icon: Percent },
	{ id: "bug", label: "Bug", Icon: Bug },
	{ id: "bug-play", label: "Bug Play", Icon: BugPlay },
	{ id: "wrench", label: "Wrench", Icon: Wrench },
	{ id: "hammer", label: "Hammer", Icon: Hammer },
	{ id: "cog", label: "Cog", Icon: Cog },
	{ id: "settings", label: "Settings", Icon: Settings },
	{ id: "settings-2", label: "Settings 2", Icon: Settings2 },
	{ id: "sliders-horizontal", label: "Sliders Horizontal", Icon: SlidersHorizontal },
	{ id: "sliders", label: "Sliders", Icon: Sliders },
	{ id: "terminal", label: "Terminal", Icon: Terminal },
	{ id: "code", label: "Code", Icon: Code },
	{ id: "code-2", label: "Code 2", Icon: Code2 },
	{ id: "git-branch", label: "Git Branch", Icon: GitBranch },
	{ id: "git-commit-horizontal", label: "Git Commit Horizontal", Icon: GitCommitHorizontal },
	{ id: "git-pull-request", label: "Git Pull Request", Icon: GitPullRequest },
	{ id: "git-merge", label: "Git Merge", Icon: GitMerge },
	{ id: "braces", label: "Braces", Icon: Braces },
	{ id: "binary", label: "Binary", Icon: Binary },
	{ id: "database", label: "Database", Icon: Database },
	{ id: "server", label: "Server", Icon: Server },
	{ id: "cpu", label: "Cpu", Icon: Cpu },
	{ id: "hard-drive", label: "Hard Drive", Icon: HardDrive },
	{ id: "cloud", label: "Cloud", Icon: Cloud },
	{ id: "cloud-upload", label: "Cloud Upload", Icon: CloudUpload },
	{ id: "users", label: "Users", Icon: Users },
	{ id: "user", label: "User", Icon: User },
	{ id: "user-plus", label: "User Plus", Icon: UserPlus },
	{ id: "user-check", label: "User Check", Icon: UserCheck },
	{ id: "users-round", label: "Users Round", Icon: UsersRound },
	{ id: "contact", label: "Contact", Icon: Contact },
	{ id: "handshake", label: "Handshake", Icon: Handshake },
	{ id: "message-square", label: "Message Square", Icon: MessageSquare },
	{ id: "message-circle", label: "Message Circle", Icon: MessageCircle },
	{ id: "messages-square", label: "Messages Square", Icon: MessagesSquare },
	{ id: "speech", label: "Speech", Icon: Speech },
	{ id: "megaphone", label: "Megaphone", Icon: Megaphone },
	{ id: "phone", label: "Phone", Icon: Phone },
	{ id: "video", label: "Video", Icon: Video },
	{ id: "calendar", label: "Calendar", Icon: Calendar },
	{ id: "calendar-days", label: "Calendar Days", Icon: CalendarDays },
	{ id: "calendar-check", label: "Calendar Check", Icon: CalendarCheck },
	{ id: "calendar-clock", label: "Calendar Clock", Icon: CalendarClock },
	{ id: "calendar-range", label: "Calendar Range", Icon: CalendarRange },
	{ id: "clock", label: "Clock", Icon: Clock },
	{ id: "clock-3", label: "Clock 3", Icon: Clock3 },
	{ id: "timer", label: "Timer", Icon: Timer },
	{ id: "hourglass", label: "Hourglass", Icon: Hourglass },
	{ id: "history", label: "History", Icon: HistoryIcon },
	{ id: "alarm-clock", label: "Alarm Clock", Icon: AlarmClock },
	{ id: "chart-bar", label: "Chart Bar", Icon: ChartBar },
	{ id: "bar-chart-3", label: "Bar Chart 3", Icon: BarChart3 },
	{ id: "chart-line", label: "Chart Line", Icon: ChartLine },
	{ id: "line-chart", label: "Line Chart", Icon: LineChart },
	{ id: "chart-pie", label: "Chart Pie", Icon: ChartPie },
	{ id: "pie-chart", label: "Pie Chart", Icon: PieChart },
	{ id: "trending-up", label: "Trending Up", Icon: TrendingUp },
	{ id: "trending-down", label: "Trending Down", Icon: TrendingDown },
	{ id: "activity", label: "Activity", Icon: Activity },
	{ id: "gauge", label: "Gauge", Icon: Gauge },
	{ id: "signal", label: "Signal", Icon: Signal },
	{ id: "radar", label: "Radar", Icon: Radar },
	{ id: "search", label: "Search", Icon: Search },
	{ id: "filter", label: "Filter", Icon: Filter },
	{ id: "funnel", label: "Funnel", Icon: Funnel },
	{ id: "eye", label: "Eye", Icon: Eye },
	{ id: "eye-off", label: "Eye Off", Icon: EyeOff },
	{ id: "bolt", label: "Bolt", Icon: Bolt },
	{ id: "lightbulb", label: "Lightbulb", Icon: Lightbulb },
	{ id: "brain", label: "Brain", Icon: Brain },
	{ id: "compass", label: "Compass", Icon: Compass },
	{ id: "map", label: "Map", Icon: MapIcon },
	{ id: "map-pin", label: "Map Pin", Icon: MapPin },
	{ id: "navigation", label: "Navigation", Icon: NavigationIcon },
	{ id: "route", label: "Route", Icon: Route },
	{ id: "waypoints", label: "Waypoints", Icon: Waypoints },
	{ id: "workflow", label: "Workflow", Icon: Workflow },
	{ id: "network", label: "Network", Icon: Network },
	{ id: "share-2", label: "Share 2", Icon: Share2 },
	{ id: "link", label: "Link", Icon: Link },
	{ id: "link-2", label: "Link 2", Icon: Link2 },
	{ id: "paperclip", label: "Paperclip", Icon: Paperclip },
	{ id: "palette", label: "Palette", Icon: Palette },
	{ id: "brush", label: "Brush", Icon: Brush },
	{ id: "paintbrush", label: "Paintbrush", Icon: Paintbrush },
	{ id: "pen-tool", label: "Pen Tool", Icon: PenTool },
	{ id: "pencil", label: "Pencil", Icon: Pencil },
	{ id: "edit-3", label: "Edit 3", Icon: Edit3 },
	{ id: "type", label: "Type", Icon: Type },
	{ id: "image", label: "Image", Icon: ImageIcon },
	{ id: "camera", label: "Camera", Icon: Camera },
	{ id: "film", label: "Film", Icon: Film },
	{ id: "music", label: "Music", Icon: Music },
	{ id: "headphones", label: "Headphones", Icon: Headphones },
	{ id: "mic", label: "Mic", Icon: Mic },
	{ id: "shopping-cart", label: "Shopping Cart", Icon: ShoppingCart },
	{ id: "shopping-bag", label: "Shopping Bag", Icon: ShoppingBag },
	{ id: "credit-card", label: "Credit Card", Icon: CreditCard },
	{ id: "dollar-sign", label: "Dollar Sign", Icon: DollarSign },
	{ id: "wallet", label: "Wallet", Icon: Wallet },
	{ id: "receipt", label: "Receipt", Icon: Receipt },
	{ id: "banknote", label: "Banknote", Icon: Banknote },
	{ id: "coins", label: "Coins", Icon: Coins },
	{ id: "briefcase", label: "Briefcase", Icon: Briefcase },
	{ id: "building", label: "Building", Icon: Building },
	{ id: "building-2", label: "Building 2", Icon: Building2 },
	{ id: "home", label: "Home", Icon: Home },
	{ id: "house", label: "House", Icon: House },
	{ id: "store", label: "Store", Icon: Store },
	{ id: "factory", label: "Factory", Icon: Factory },
	{ id: "warehouse", label: "Warehouse", Icon: Warehouse },
	{ id: "shield", label: "Shield", Icon: Shield },
	{ id: "shield-check", label: "Shield Check", Icon: ShieldCheck },
	{ id: "lock", label: "Lock", Icon: Lock },
	{ id: "unlock", label: "Unlock", Icon: Unlock },
	{ id: "key", label: "Key", Icon: Key },
	{ id: "key-round", label: "Key Round", Icon: KeyRound },
	{ id: "fingerprint", label: "Fingerprint", Icon: Fingerprint },
	{ id: "scan-face", label: "Scan Face", Icon: ScanFace },
	{ id: "truck", label: "Truck", Icon: Truck },
	{ id: "plane", label: "Plane", Icon: Plane },
	{ id: "car", label: "Car", Icon: Car },
	{ id: "bike", label: "Bike", Icon: Bike },
	{ id: "ship", label: "Ship", Icon: Ship },
	{ id: "globe", label: "Globe", Icon: Globe },
	{ id: "globe-2", label: "Globe 2", Icon: Globe2 },
	{ id: "languages", label: "Languages", Icon: Languages },
	{ id: "plug", label: "Plug", Icon: Plug },
	{ id: "power", label: "Power", Icon: Power },
	{ id: "battery", label: "Battery", Icon: Battery },
	{ id: "wifi", label: "Wifi", Icon: Wifi },
	{ id: "rss", label: "Rss", Icon: Rss },
	{ id: "leaf", label: "Leaf", Icon: Leaf },
	{ id: "tree-pine", label: "Tree Pine", Icon: TreePine },
	{ id: "flower-2", label: "Flower 2", Icon: Flower2 },
	{ id: "sun", label: "Sun", Icon: Sun },
	{ id: "moon", label: "Moon", Icon: Moon },
	{ id: "cloud-rain", label: "Cloud Rain", Icon: CloudRain },
	{ id: "snowflake", label: "Snowflake", Icon: Snowflake },
	{ id: "droplet", label: "Droplet", Icon: Droplet },
	{ id: "wind", label: "Wind", Icon: Wind },
	{ id: "mountain", label: "Mountain", Icon: Mountain },
	{ id: "waves", label: "Waves", Icon: Waves },
	{ id: "anchor", label: "Anchor", Icon: Anchor },
	{ id: "coffee", label: "Coffee", Icon: Coffee },
	{ id: "pizza", label: "Pizza", Icon: Pizza },
	{ id: "apple", label: "Apple", Icon: Apple },
	{ id: "utensils", label: "Utensils", Icon: Utensils },
	{ id: "cake", label: "Cake", Icon: Cake },
	{ id: "beer", label: "Beer", Icon: Beer },
	{ id: "dumbbell", label: "Dumbbell", Icon: Dumbbell },
	{ id: "footprints", label: "Footprints", Icon: Footprints },
	{ id: "puzzle", label: "Puzzle", Icon: Puzzle },
	{ id: "gamepad-2", label: "Gamepad 2", Icon: Gamepad2 },
	{ id: "dice-5", label: "Dice 5", Icon: Dice5 },
	{ id: "swords", label: "Swords", Icon: Swords },
	{ id: "wand-2", label: "Wand 2", Icon: Wand2 },
	{ id: "ghost", label: "Ghost", Icon: Ghost },
	{ id: "bot", label: "Bot", Icon: Bot },
	{ id: "atom", label: "Atom", Icon: Atom },
	{ id: "flask-conical", label: "Flask Conical", Icon: FlaskConical },
	{ id: "microscope", label: "Microscope", Icon: Microscope },
	{ id: "telescope", label: "Telescope", Icon: Telescope },
	{ id: "beaker", label: "Beaker", Icon: Beaker },
	{ id: "stethoscope", label: "Stethoscope", Icon: Stethoscope },
	{ id: "pill", label: "Pill", Icon: Pill },
	{ id: "heart-pulse", label: "Heart Pulse", Icon: HeartPulse },
	{ id: "thumbs-up", label: "Thumbs Up", Icon: ThumbsUp },
	{ id: "smile", label: "Smile", Icon: Smile },
	{ id: "laugh", label: "Laugh", Icon: Laugh },
	{ id: "party-popper", label: "Party Popper", Icon: PartyPopper },
	{ id: "gift", label: "Gift", Icon: Gift },
	{ id: "volume-2", label: "Volume 2", Icon: Volume2 },
	{ id: "play", label: "Play", Icon: Play },
	{ id: "pause", label: "Pause", Icon: Pause },
	{ id: "skip-forward", label: "Skip Forward", Icon: SkipForward },
	{ id: "repeat", label: "Repeat", Icon: Repeat },
	{ id: "shuffle", label: "Shuffle", Icon: Shuffle },
	{ id: "arrow-right", label: "Arrow Right", Icon: ArrowRight },
	{ id: "arrow-up-right", label: "Arrow Up Right", Icon: ArrowUpRight },
	{ id: "corner-down-right", label: "Corner Down Right", Icon: CornerDownRight },
	{ id: "move", label: "Move", Icon: Move },
	{ id: "maximize-2", label: "Maximize 2", Icon: Maximize2 },
	{ id: "minimize-2", label: "Minimize 2", Icon: Minimize2 },
	{ id: "expand", label: "Expand", Icon: Expand },
	{ id: "shrink", label: "Shrink", Icon: Shrink },
	{ id: "refresh-cw", label: "Refresh Cw", Icon: RefreshCw },
	{ id: "rotate-cw", label: "Rotate Cw", Icon: RotateCw },
	{ id: "undo-2", label: "Undo 2", Icon: Undo2 },
	{ id: "redo-2", label: "Redo 2", Icon: Redo2 },
	{ id: "download", label: "Download", Icon: Download },
	{ id: "upload", label: "Upload", Icon: Upload },
	{ id: "save", label: "Save", Icon: Save },
	{ id: "trash-2", label: "Trash 2", Icon: Trash2 },
	{ id: "copy", label: "Copy", Icon: Copy },
	{ id: "scissors", label: "Scissors", Icon: Scissors },
	{ id: "check-check", label: "Check Check", Icon: CheckCheck },
	{ id: "check", label: "Check", Icon: Check },
	{ id: "x", label: "X", Icon: X },
	{ id: "plus", label: "Plus", Icon: Plus },
	{ id: "minus", label: "Minus", Icon: Minus },
];

const BY_ID = new Map(ICONS.map((entry) => [entry.id, entry.Icon]));

export function Icon({
	id,
	fallback = "list",
	size = 14,
	className,
}: {
	id?: string;
	fallback?: string;
	size?: number;
	className?: string;
}) {
	const Component = BY_ID.get(id ?? "") ?? BY_ID.get(fallback) ?? List;
	return <Component size={size} className={className} />;
}

/** The searchable grid. Rendered inside `IconField`'s popover. */
export function IconPicker({
	value,
	onChange,
}: {
	value: string | undefined;
	onChange: (id: string) => void;
}) {
	const [query, setQuery] = useState("");

	const matches = useMemo(() => {
		const needle = query.trim().toLowerCase();
		if (!needle) return ICONS;
		return ICONS.filter(
			(entry) =>
				entry.id.includes(needle) || entry.label.toLowerCase().includes(needle),
		);
	}, [query]);

	return (
		<div className="vf-icon-picker">
			<input
				type="text"
				className="vf-input vf-icon-search"
				autoFocus
				placeholder="Search icons…"
				value={query}
				onChange={(event) => setQuery(event.target.value)}
			/>
			<div className="vf-icon-grid" role="listbox" aria-label="Icon">
				{matches.map(({ id, label, Icon: Component }) => (
					<button
						key={id}
						type="button"
						role="option"
						aria-selected={value === id}
						className={`vf-icon-option${value === id ? " is-on" : ""}`}
						title={label}
						onClick={() => onChange(id)}
					>
						<Component size={16} />
					</button>
				))}
				{matches.length === 0 && (
					<p className="vf-icon-empty">No icons match "{query}".</p>
				)}
			</div>
		</div>
	);
}

/**
 * The current icon as a button; clicking it opens the full picker. Keeps the
 * dialogs compact — a 280-icon grid shouldn't be the first thing you see.
 */
export function IconField({
	value,
	fallback,
	onChange,
}: {
	value: string | undefined;
	fallback?: string;
	onChange: (id: string) => void;
}) {
	const [open, setOpen] = useState(false);

	useEffect(() => {
		if (!open) return;
		const close = () => setOpen(false);
		const id = window.setTimeout(() => window.addEventListener("click", close));
		return () => {
			window.clearTimeout(id);
			window.removeEventListener("click", close);
		};
	}, [open]);

	return (
		<div className="vf-icon-field">
			<button
				type="button"
				className={`vf-icon-trigger${open ? " is-on" : ""}`}
				title="Choose an icon"
				aria-label="Choose an icon"
				aria-expanded={open}
				onClick={(event) => {
					event.stopPropagation();
					setOpen((current) => !current);
				}}
			>
				<Icon id={value} fallback={fallback} size={18} />
			</button>

			{open && (
				<div
					className="vf-icon-popover"
					onClick={(event) => event.stopPropagation()}
				>
					<IconPicker
						value={value}
						onChange={(id) => {
							onChange(id);
							setOpen(false);
						}}
					/>
				</div>
			)}
		</div>
	);
}
